---
- name: Install Apache
  apt:
        name: "apache2"
        state: latest
  become: true

- name: Start Apache
  service:
          name: apache2
          state: started
          enabled: true
  become: true
# tasks file for vagrant02.role
